void setup(){
  Serial.begin(230400);
}

void loop(){
  Serial.print(millis());
  Serial.print(",");
  Serial.print(random(0,3000));//RPM
  Serial.print(",");
  Serial.print(random(0,100));//motorTemp
  Serial.print(",");
  Serial.print(random(0,100));//speed_FL
  Serial.print(",");
  Serial.print(random(0,100));//speed_FR
  Serial.print(",");
  Serial.print(random(0,100));//speed_RL
  Serial.print(",");
  Serial.print(random(0,100));//speed_RR
  Serial.print(",");
  Serial.print(random(0,100));//speed
  Serial.print(",");
  Serial.print(random(0,50));//brakepress
  Serial.print(",");
  Serial.print(13.4);//LVbattery
  Serial.print(",");
  Serial.print(random(0,100));//throttle position
  Serial.print(",");
  Serial.print("0");//datalogging
  Serial.print(",");
  Serial.print(random(-100,100));//damper_FL
  Serial.print(",");
  Serial.print(random(-100,100));//damper_FR
  Serial.print(",");
  Serial.print(random(-100,100));//damper_RL
  Serial.print(",");
  Serial.print(random(-100,100));//damper_RR
  Serial.print(",");
  Serial.print(random(-10,10));//pitch
  Serial.print(",");
  Serial.print(random(-10,10));//roll
  Serial.print(",");
  Serial.print(random(0,200));//FL_loadcell
  Serial.print(",");
  Serial.print(random(0,200));//FR_loadcell
  Serial.print(",");
  Serial.print(random(0,200));//RL_loadcell
  Serial.print(",");
  Serial.print(random(0,200));//RR_loadcell
  Serial.print(",");
  Serial.print(random(-3,3));//Ax
  Serial.print(",");
  Serial.print(random(-3,3));//Ay
  Serial.print(",");
  Serial.print(random(0,100));//SOC
  Serial.print(",");
  Serial.print(random(0,150));//TS_Temp
  Serial.print(",");
  Serial.print(random(0,4));//TS_Current
  Serial.print(",");
  Serial.print(random(0,300));//TS_voltage
  Serial.print(",");
  Serial.print(random(-90,90));//steering_angle
  Serial.print(",");
  Serial.println(random(0,80));//Power to motor
  delay(100);
}